# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rime
else:
    import _rime

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


RIME_DATA_DIR = _rime.RIME_DATA_DIR
RIME_USER_DIR = _rime.RIME_USER_DIR
TMUX_RIME_VERSION = _rime.TMUX_RIME_VERSION
class TmuxRime(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    session_id = property(_rime.TmuxRime_session_id_get, _rime.TmuxRime_session_id_set)
    api = property(_rime.TmuxRime_api_get, _rime.TmuxRime_api_set)
    first_run = property(_rime.TmuxRime_first_run_get, _rime.TmuxRime_first_run_set)

    def __init__(self):
        _rime.TmuxRime_swiginit(self, _rime.new_TmuxRime())
    __swig_destroy__ = _rime.delete_TmuxRime

# Register TmuxRime in _rime:
_rime.TmuxRime_swigregister(TmuxRime)


def tmux_rime_notification_handler(arg1, arg2, arg3, arg4):
    return _rime.tmux_rime_notification_handler(arg1, arg2, arg3, arg4)

def tmux_rime_process_key(arg1, arg2, arg3):
    return _rime.tmux_rime_process_key(arg1, arg2, arg3)

def tmux_rime_get_commit(arg1):
    return _rime.tmux_rime_get_commit(arg1)

def tmux_rime_get_schemas(arg1):
    return _rime.tmux_rime_get_schemas(arg1)

def tmux_rime_set_schema(arg1, arg2):
    return _rime.tmux_rime_set_schema(arg1, arg2)

def tmux_rime_start(arg1, arg2):
    return _rime.tmux_rime_start(arg1, arg2)

def tmux_rime_finish(arg1):
    return _rime.tmux_rime_finish(arg1)

def tmux_rime_init():
    return _rime.tmux_rime_init()


